# Use a base image of Node.js
FROM node:18.12

# Set the working directory
WORKDIR /

# Copy package.json and package-lock.json
COPY ../package*.json ./

# Clean npm cache
RUN npm cache clean --force

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY ../ ./

# Expose the port that the application will use
EXPOSE 3000

CMD [ "npm", "run", "start" ]