### Plugin: Rest Client 

GET http://localhost:3000/


### Auth ###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "user3@gmail.com",
  "password": "1234"
}
###

### USER ###
GET http://localhost:3000/users
Authorization: Basic: <email>:<password>


###
GET http://localhost:3000/users?page=2&limit=2
Authorization: Basic: <email>:<password>

###

GET http://localhost:3000/users/1
Authorization: Basic: <email>:<password>

### Create User
POST http://localhost:3000/users/
Content-Type: application/json

{
  "email": "user4@gmail.com",
  "name": "User 4",
  "password": "1234",
  "address": "Calle 4",
  "phone": "4123456789",
  "city": "Lima",
  "country": "Peru"
}
###
PUT http://localhost:3000/users/1
Content-Type: application/json
Authorization: Basic: <email>:<password>

{
  "email": "user4@gmail.com",
  "name": "Modifyied User 4",
  "address": "Calle 4",
  "phone": "4123456789",
  "country": "Salvador"
}
###
DELETE http://localhost:3000/users/4
Authorization: Basic: <email>:<password>

### CATEGORY ###
Get http://localhost:3000/categories
###
Post http://localhost:3000/categories/seeder
###


### PRODUCTS ###
POST http://localhost:3000/products/seeder
###

GET http://localhost:3000/products

###
GET http://localhost:3000/products?page=1&limit=5

###
GET http://localhost:3000/products/1
###
POST http://localhost:3000/products/
Content-Type: application/json
Authorization: Basic: <email>:<password>

{
  "name": "Product 4",
  "description": "Product 4",
  "price": 20,
  "stock": true,
  "imgUrl": "http://google.com/imagen4"
}

###
PUT http://localhost:3000/products/1
Content-Type: application/json
Authorization: Basic: <email>:<password>

{
  "name": "Modifyed Product 1",
  "description": "Product 1",
  "price": 20,
  "stock": true,
  "imgUrl": "http://google.com/imagen4"
}
###
DELETE http://localhost:3000/products/1
Authorization: Basic: <email>:<password>


### ORDERS ###

### Create user
POST http://localhost:3000/users/
Content-Type: application/json
Authorization: Basic: <email>:<password>

{
  "email": "user7@gmail.com",
  "name": "User 7",
  "address": "Calle 7",
  "password":"1234",
  "phone": "4123456789",
  "country": "Peru",
  "city":"Lima"
}

### Product Seeder 
POST http://localhost:3000/products/seeder

### Product List
GET http://localhost:3000/products

###Create order
POST http://localhost:3000/orders/
Content-Type: application/json

{
  "userId": "c79d4dcf-beb2-44f1-9d7a-839c870c9e47",
  "products":[
    {
      "id":"ec3a0d37-0c59-4c04-b5f4-d9cb5d2c01e2"
    },
    {
      "id":"f5ca0ece-4cc5-4655-93c8-f4dab07c0507"
    }
  ]
}

###
GET http://localhost:3000/orders/cbf6f996-a2dd-45eb-a615-96b3cf3fdefc

###
GET http://localhost:3000/orderDetails/
